# Generated by Django 2.0.7 on 2018-07-05 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('df_goods', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GoogsInfo',
            new_name='GoodsInfo',
        ),
    ]
