# Generated by Django 2.0.7 on 2018-07-10 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('df_goods', '0002_auto_20180705_1834'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goodsinfo',
            options={'ordering': ['id', 'gprice', 'gkucun', 'gclick']},
        ),
        migrations.AlterModelOptions(
            name='typeinfo',
            options={'ordering': ['id']},
        ),
    ]
