# Generated by Django 2.0.7 on 2018-07-03 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=20)),
                ('upwd', models.CharField(max_length=40)),
                ('uemail', models.EmailField(max_length=254)),
                ('uphone', models.CharField(max_length=11)),
                ('uaddress', models.CharField(max_length=100)),
                ('upostcode', models.CharField(max_length=6)),
                ('urecipients', models.CharField(max_length=20)),
            ],
        ),
    ]
