# Generated by Django 2.0.7 on 2018-07-23 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('df_order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetailinfo',
            old_name='oder',
            new_name='order',
        ),
    ]
